apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-r8la
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-r8la
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-r8la
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-r8la
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-r8la
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-epbp-tenant/rhtap-demo-app/hacbs-test-project-r8la@sha256:f57739b1a60bcce1d948d0a6a5825f1f342bd58f884a808708e418c62a3ed303
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
