apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-r8la
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-epbp-tenant/rhtap-demo-app/hacbs-test-project-r8la@sha256:f57739b1a60bcce1d948d0a6a5825f1f342bd58f884a808708e418c62a3ed303
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
